### ISSUE TITLE
tweet-emotion 

### ISSUE THREAD

**Issue by patilshilpa** [pubnub/tweet-emotion#2]
how to run in the node.js anybody

**Comment by stephenlb** [comment]
You can do:

```javascript
require("pubnub")({
subscribe_key: 'sub-c-78806dd4-42a6-11e4-aed8-02ee2ddab7fe'
}).subscribe({
channel : 'pubnub-twitter',
message : function(msg){ console.log(msg) }
});
```

**Comment by patilshilpa** [comment]
thank you for your reply i used the above code in app.js  and i install npm install pubnub stil it giving me error. my npm could start what is the command to run this app . i used npm start and node app.js both or not working me please stephenlp can help me .

**Comment by girliemac** [comment]
This app doesn't require Node.js. 
I am not exactly sure if I am getting your question correctly, but are you trying to convert this app into a node.js app? 

As Stephen said, to use PubNub in Node.js, yes, `npm install pubnub` should get you what you need to run PubNub with Node. But to convert this app into a Node app, you can't just swap the pubnub.js (front-end JavaScript) to the mode module.

**Comment by patilshilpa** [comment]
k  stephen    tell me how i to run this app in my machine what i need follow  the step. can you guide me ..

**Comment by keyosk** [comment]
@patilshilpa you are attempting to launch your node.js app using `npm`. this is where your problem is, `npm` is not the node.js interpreter, it is the node package manager, it is used to install node packages. You instead want to use `node`. If your script is named app.js, you will want to run the command `node app.js` This article may help you: http://www.nodebeginner.org/#hello-world

**Comment by patilshilpa** [comment]
ok thank you i will try to implement it .

**Comment by patilshilpa** [comment]
how to assign the   javascript variable to html  using jquery can anybody guide me
